### ISSUE TITLE
sbig utils are quiet.

### ISSUE THREAD

**Issue by andrewtubbiolo** [garlick/sbig-util#42]
Hello:

 I have the various test programs working in the sbig-parport module. I can see the functionality on my logic analyser. However none of the sbig util's seems to be addressing the virtual parallel port. In the .sbig/config.ini I've tried setting the port to LPT1, sbiglpt0, and parport0. what should I put here? Also I need to keep doing a mknod on /dev/sbiglpt0 even though sbiglpt.ko is inserting into the kernel. I can't seem to find any log files with applicable messages. What log files should be being written to? I'm using a v2 hardware, and libsbigudrv.so.2.

**Comment by garlick** [comment]
LPT1 is what you want in the sbig-util config file or on the command line.  That's the form wanted by the libsbigudrv.so, which is what opens /dev/sbiglpt0.

Sorry about the device creation problem.  I did it right initially (in sbig-parport) but then when DL wouldn't release their part of the code as GPL, I had to back it out because it requires "GPL only" kernel symbols.  Just uncomment the EXTRA_CFLAGS in the driver Makefile and rebuild to get that working if you like.

Logging is to the kernel dmesg so check with dmesg command or wherever your kernel logs are going.

**Comment by andrewtubbiolo** [comment]
Of course, the old PC DOS did not index starting with zero.

I uncommented the extra_cflags in the Makefile and rebuilt sbiglpt.ko file. I also double checked the udev rules are still there, and no dice. I still have to make the /dev/sbiglpt0 file by hand after a reboot. I'm depending on an error message I got earlier in the process that hinted at 

mknod c /dev/sbiglpt0 240 0

as a means of making the file manually. Is that correct a character device? are the major and minor numbers right? If that depends, how do I find out what they need to be?

I'm still not getting any feedback via logs.

**Comment by garlick** [comment]
So parport is loaded and nothing else is claiming it right?  (like lp or ppdev)?
When you load sbiglpt.ko, dmesg should show it claiming it, something like:
```
sbiglpt0: using parport0
```

I don't have hardware with me right now but I'll dig some more.

**Comment by andrewtubbiolo** [comment]
.... Thank You! Yes, I had automated the loading of the modules over the months I've been working on this. And as soon as I removed lp, ppdev, sbiglpt, then reloaded sbiglpt.ko I saw activity on the outputs. I'll hook up the camera tomorrow and see what I can see. 

Thanks Again. 
Andrew

**Comment by garlick** [comment]
> Of course, the old PC DOS did not index starting with zero.

I think actually they were (irritatingly) origin 1, e.g. LPT1, LPT2, LPT3

(I had to check)

https://en.wikipedia.org/wiki/Parallel_port
